services:
  mario-train-mac:
    build:
      context: .
      platforms:
        - linux/arm64
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../models:/app/models
      - ./tensorboard:/app/tensorboard
    ports:
      - "8080:8080"
      - "6006:6006"
    shm_size: '4gb'
    command: >
      bash -c "python -m tensorboard.main --logdir /app/tensorboard --host 0.0.0.0 --port 6006 &
               python train.py"
