services:
  mario-train-cpu:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - N_ENVS=4
    volumes:
      - ../models:/app/models
      - ./tensorboard:/app/tensorboard
    ports:
      - "8081:8080"
      - "6007:6006"
    shm_size: '2gb'
